WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

# Ascii
DELETE_KEY = 127
BACKSPACE_KEY = 8
ZERO = 1073741922
ONE = 1073741913
NINE = 1073741921

# Textbox
TEXTBOX_TEXT_SIZE = 28
TEXT_MAX_LENGTH = 18

# Database
EMPLOYEES_FILE_PATH = "files/employees.txt"
TASKS_FILE_PATH = "files/tasks.txt"

# Loading screen
AMOUNT_OF_LOADING_SCREENS = 17
LOADING_SCREEN_IMAGE_PATH = "./images/loading_screen/loading_image"
LOADING_SCREEN_PATH_EXTENSION = ".jpg"

# Login screen
LOGIN_BACKGROUND_IMAGE = "./images/login_screen/login_background.jpg"
# Login text boxes
SIGN_IN_TEXTBOX_X_POS = 530
USERNAME_TEXTBOX_Y_POS = 278
SIGN_IN_TEXTBOX_WIDTH = 218
SIGN_IN_TEXTBOX_HEIGHT = 29
PASSWORD_TEXTBOX_Y_POS = 371
# Login button
LOGIN_BTN_IMAGE = "./images/login_screen/login_btn.png"
LOGIN_BTN_X_POS = 575
LOGIN_BTN_Y_POS = 425
LOGIN_BTN_WIDTH = 126
LOGIN_BTN_HEIGHT = 61

# Task manager screen
TASK_MANAGER_BACKGROUND_IMAGE = "./images/task_manager_screen/task_manager_background.jpg"
# List of tasks
MAX_NUM_OF_TASKS = 8
START_Y_POS_FOR_TASKS = 188
SPACE_BETWEEN_TASK_LINES = 32
X_POS_FOR_TASK_ID = 585
X_POS_FOR_DETAILS = 690
X_POS_FOR_STATUS = 1074
# Status images
V_IMAGE = "./images/task_manager_screen/V.png"
X_IMAGE = "./images/task_manager_screen/X.png"
START_IMAGE_WIDTH = 28
START_IMAGE_HEIGHT = 26

# Add new employee button
ADD_NEW_EMPLOYEE_BTN_IMAGE = "./images/task_manager_screen/add_new_employee.png"
ADD_NEW_EMPLOYEE_BTN_X_POS = 100
ADD_NEW_EMPLOYEE_BTN_Y_POS = 450
ADD_NEW_EMPLOYEE_BTN_WIDTH = 186
ADD_NEW_EMPLOYEE_BTN_HEIGHT = 53
# Complete task button
COMPLETE_TASK_BTN_IMAGE = "./images/task_manager_screen/complete_task.png"
COMPLETE_TASK_BTN_X_POS = 560
COMPLETE_TASK_BTN_Y_POS = 515
COMPLETE_TASK_BTN_WIDTH = 162
COMPLETE_TASK_BTN_HEIGHT = 45
# Add new task button
ADD_NEW_TASK_BTN_IMAGE = "./images/task_manager_screen/add_new_task.png"
ADD_NEW_TASK_BTN_X_POS = 750
ADD_NEW_TASK_BTN_Y_POS = 515
ADD_NEW_TASK_BTN_WIDTH = 167
ADD_NEW_TASK_BTN_HEIGHT = 45
# Delete task button
DELETE_TASK_BTN_IMAGE = "./images/task_manager_screen/delete_task.png"
DELETE_TASK_BTN_X_POS = 945
DELETE_TASK_BTN_Y_POS = 515
DELETE_TASK_BTN_WIDTH = 143
DELETE_TASK_BTN_HEIGHT = 45
# Text boxes location
DETAILS_X_POS = 250
FIRST_NAME_Y_POS = 179
LAST_NAME_Y_POS = 224
ID_NUMBER_Y_POS = 270
EMPLOYEE_ID_Y_POS = 314
MANAGER_ID_Y_POS = 359
DETAILS_TEXT_SIZE = 22

# Complete task screen
COMPLETE_TASK_SCREEN_BACKGROUND_IMAGE = "./images/complete_task_screen/complete_task_background.jpg"
# Complete button
COMPLETE_BTN_X_POS = 550
COMPLETE_BTN_Y_POS = 460
COMPLETE_BTN_WIDTH = 191
COMPLETE_BTN_HEIGHT = 68
COMPLETE_BTN_IMAGE = "./images/complete_task_screen/complete.png"
# Complete task text boxes
COMPLETE_TASK_TEXTBOX_X_POS = 575
COMPLETE_TASK_TASK_ID_TEXTBOX_Y_POS = 300
COMPLETE_TASK_TEXTBOX_WIDTH = 240
COMPLETE_TASK_TEXTBOX_HEIGHT = 29
COMPLETE_TASK_SECURITY_KEY_TEXTBOX_Y_POS = 350


# Add new task screen
ADD_NEW_TASK_SCREEN_BACKGROUND_IMAGE = "./images/add_new_task_screen/add_new_task_background.jpg"
# Add new task button
ADD_NEW_TASK_IN_ADD_SCREEN_BTN_IMAGE = "./images/add_new_task_screen/new_task.png"
ADD_NEW_TASK_IN_ADD_SCREEN_BTN_X_POS = 520
ADD_NEW_TASK_IN_ADD_SCREEN_BTN_Y_POS = 490
ADD_NEW_TASK_IN_ADD_SCREEN_BTN_WIDTH = 243
ADD_NEW_TASK_IN_ADD_SCREEN_BTN_HEIGHT = 64
# Add new task text boxes
ADD_NEW_TASK_TEXTBOX_X_POS = 570
ADD_NEW_TASK_EMPLOYEE_ID_TEXTBOX_Y_POS = 190
ADD_NEW_TASK_TEXTBOX_WIDTH = 245
ADD_NEW_TASK_TEXTBOX_HEIGHT = 29
ADD_NEW_TASK_TASK_TYPE_TEXTBOX_Y_POS = 235
DESCRIPTION_MAX_LENGTH_IN_LINE = 25
DESCRIPTION_MAX_LINES = 4
ADD_NEW_TASK_DESCRIPTION_TEXTBOX_X_POS = 470
ADD_NEW_TASK_DESCRIPTION_TEXTBOX_Y_POS = 330
ADD_NEW_TASK_DESCRIPTION_TEXTBOX_WIDTH = 340
ADD_NEW_TASK_DESCRIPTION_TEXTBOX_HEIGHT = ADD_NEW_TASK_TEXTBOX_HEIGHT * DESCRIPTION_MAX_LINES


# Delete task screen
DELETE_TASK_SCREEN_BACKGROUND_IMAGE = "./images/delete_task_screen/delete_task_background.jpg"
# Delete button
DELETE_BTN_X_POS = 550
DELETE_BTN_Y_POS = 465
DELETE_BTN_WIDTH = 183
DELETE_BTN_HEIGHT = 60
DELETE_BTN_IMAGE = "./images/delete_task_screen/delete.png"
# Delete task text boxes
DELETE_TASK_TEXTBOX_X_POS = 570
DELETE_TASK_TEXTBOX_WIDTH = 245
DELETE_TASK_TEXTBOX_HEIGHT = 29
DELETE_TASK_EMPLOYEE_ID_TEXTBOX_Y_POS = 300
DELETE_TASK_TASK_ID_TEXTBOX_Y_POS = 348

# Add new employee screen
ADD_NEW_EMPLOYEE_SCREEN_BACKGROUND_IMAGE = "./images/add_new_employee_screen/add_new_employee_background.jpg"
# Add new employee button
ADD_NEW_EMPLOYEE_IN_ADD_SCREEN_BTN_IMAGE = "./images/add_new_employee_screen/add_new_employee.png"
ADD_NEW_EMPLOYEE_IN_ADD_SCREEN_BTN_X_POS = 500
ADD_NEW_EMPLOYEE_IN_ADD_SCREEN_BTN_Y_POS = 500
ADD_NEW_EMPLOYEE_IN_ADD_SCREEN_BTN_WIDTH = 284
ADD_NEW_EMPLOYEE_IN_ADD_SCREEN_BTN_HEIGHT = 81
# Add new employee text boxes
ADD_NEW_EMPLOYEE_TEXTBOX_X_POS = 565
ADD_NEW_EMPLOYEE_TEXTBOX_WIDTH = 248
ADD_NEW_EMPLOYEE_TEXTBOX_HEIGHT = 29
ADD_NEW_EMPLOYEE_FIRST_NAME_TEXTBOX_Y_POS = 202
ADD_NEW_EMPLOYEE_LAST_NAME_TEXTBOX_Y_POS = 252
ADD_NEW_EMPLOYEE_ID_NUMBER_TEXTBOX_Y_POS = 302
ADD_NEW_EMPLOYEE_MANAGER_ID_TEXTBOX_Y_POS = 352
ADD_NEW_EMPLOYEE_ROLE_TEXTBOX_Y_POS = 402

# General images

# Back button
BACK_BTN_IMAGE = "./images/general_images/back.png"
BACK_BTN_X_POS = 30
BACK_BTN_Y_POS = 40
BACK_BTN_WIDTH = 95
BACK_BTN_HEIGHT = 99
# Logo
LOGO_IMAGE = "./images/general_images/logo.png"
LOGO_IMAGE_X_POS = 1160
LOGO_IMAGE_Y_POS = 40
LOGO_IMAGE_WIDTH = 98
LOGO_IMAGE_HEIGHT = 97


# Errors
ERROR_X_POS = 0
ERROR_Y_POS = 585
ERROR_WIDTH = WINDOW_WIDTH
ERROR_HEIGHT = 60
# Wrong_username_or_password
WRONG_USERNAME_OR_PASSWORD_ERROR = "images/errors/wrong_username_or_password.jpg"
EMPTY_FIELDS_ERROR = "images/errors/empty_fields.jpg"
TASK_TYPE_DOESNT_FIT_ERROR = "images/errors/task_type_doesnt_fit.jpg"
EMPLOYEES_ID_DOESNT_EXIST_ERROR = "images/errors/employees_id_doesnt_exist.jpg"
TASK_DOESNT_EXIST_ERROR = "images/errors/task_doesnt_exist.jpg"
INCORRECT_SECURITY_KEY_ERROR = "images/errors/incorrect_security_key.jpg"
WRONG_FORMAT_ERROR = "images/errors/wrong_format.jpg"
MANAGERS_ID_DOESNT_EXIST_ERROR = "images/errors/managers_id_doesnt_exist.jpg"

# Database
FIRST_NAME_INDEX = 0
LAST_NAME_INDEX = 1
ID_INDEX = 2
EMPLOYEES_ID_INDEX = 3
MANAGERS_ID_INDEX = 4
ROLE_INDEX = 5

TASK_FILE_TASK_ID_INDEX = 0
TASK_FILE_EMPLOYEES_ID_INDEX = 1
TASK_FILE_TASK_TYPE = 2
TASK_FILE_DESCRIPTION = 3
TASK_FILE_STATUS = 4
